<?php

namespace Database\Seeders;

use App\Models\Recipe;
use Illuminate\Database\Seeder;

/**
 * Seeder de recetas. Incluye ~50 recetas variadas
 * organizadas por categoría. Los macros son POR PORCIÓN.
 * Recetas pensadas para una dieta fitness / deportista.
 */
class RecipesTableSeeder extends Seeder
{
    public function run(): void
    {
        $recipes = [
            // =====================================================================
            // DESAYUNOS
            // =====================================================================
            [
                'name'                  => 'Tortitas de avena y plátano',
                'description'           => 'Tortitas esponjosas sin harina, ideales para recargar energía por la mañana.',
                'category'              => 'desayuno',
                'calories_per_serving'  => 310,
                'protein_per_serving'   => 15,
                'carbs_per_serving'     => 45,
                'fat_per_serving'       => 7,
                'fiber_per_serving'     => 5,
                'servings'              => 2,
                'prep_time_min'         => 5,
                'cook_time_min'         => 10,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Copos de avena', 'quantity' => '80g'],
                    ['name' => 'Plátano maduro', 'quantity' => '1 unidad (100g)'],
                    ['name' => 'Huevo', 'quantity' => '2 unidades'],
                    ['name' => 'Canela en polvo', 'quantity' => '1 cucharadita'],
                ],
                'instructions'          => "1. Tritura el plátano con un tenedor hasta obtener un puré.\n2. Mezcla el puré con los huevos y la avena hasta obtener una masa homogénea.\n3. Añade la canela y mezcla bien.\n4. Calienta una sartén antiadherente a fuego medio-bajo con un poco de aceite.\n5. Vierte pequeñas porciones de masa y cocina 2-3 minutos por cada lado hasta que estén doradas.",
            ],
            [
                'name'                  => 'Porridge de avena con frutas',
                'description'           => 'Desayuno caliente y nutritivo con avena, leche y frutas frescas.',
                'category'              => 'desayuno',
                'calories_per_serving'  => 380,
                'protein_per_serving'   => 14,
                'carbs_per_serving'     => 62,
                'fat_per_serving'       => 8,
                'fiber_per_serving'     => 6,
                'servings'              => 1,
                'prep_time_min'         => 2,
                'cook_time_min'         => 5,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Copos de avena', 'quantity' => '80g'],
                    ['name' => 'Leche semidesnatada', 'quantity' => '200ml'],
                    ['name' => 'Plátano', 'quantity' => '1/2 unidad'],
                    ['name' => 'Arándanos', 'quantity' => '50g'],
                    ['name' => 'Miel', 'quantity' => '1 cucharadita'],
                ],
                'instructions'          => "1. En un cazo pequeño, mezcla la avena con la leche.\n2. Cocina a fuego medio removiendo constantemente durante 3-5 minutos hasta que espese.\n3. Sirve en un bol y añade por encima el plátano en rodajas, los arándanos y la miel.",
            ],
            [
                'name'                  => 'Tostadas con aguacate y huevo',
                'description'           => 'Clásico desayuno fitness con grasas saludables y proteína.',
                'category'              => 'desayuno',
                'calories_per_serving'  => 420,
                'protein_per_serving'   => 20,
                'carbs_per_serving'     => 30,
                'fat_per_serving'       => 24,
                'fiber_per_serving'     => 8,
                'servings'              => 1,
                'prep_time_min'         => 5,
                'cook_time_min'         => 5,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Pan integral', 'quantity' => '2 rebanadas (80g)'],
                    ['name' => 'Aguacate', 'quantity' => '1/2 unidad (80g)'],
                    ['name' => 'Huevo', 'quantity' => '2 unidades'],
                    ['name' => 'Sal y pimienta', 'quantity' => 'al gusto'],
                    ['name' => 'Zumo de limón', 'quantity' => 'unas gotas'],
                ],
                'instructions'          => "1. Tuesta las rebanadas de pan integral.\n2. Aplasta el aguacate con un tenedor, añade unas gotas de limón, sal y pimienta.\n3. Cocina los huevos (revueltos, fritos o pochados según preferencia).\n4. Extiende el aguacate sobre las tostadas y coloca los huevos encima.",
            ],
            [
                'name'                  => 'Smoothie de proteínas',
                'description'           => 'Batido rápido post-entreno con proteína, plátano y mantequilla de cacahuete.',
                'category'              => 'desayuno',
                'calories_per_serving'  => 480,
                'protein_per_serving'   => 38,
                'carbs_per_serving'     => 50,
                'fat_per_serving'       => 12,
                'fiber_per_serving'     => 4,
                'servings'              => 1,
                'prep_time_min'         => 3,
                'cook_time_min'         => 0,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Plátano congelado', 'quantity' => '1 unidad (100g)'],
                    ['name' => 'Proteína whey (vainilla)', 'quantity' => '30g'],
                    ['name' => 'Leche semidesnatada', 'quantity' => '200ml'],
                    ['name' => 'Mantequilla de cacahuete', 'quantity' => '1 cucharada (15g)'],
                ],
                'instructions'          => "1. Añade todos los ingredientes a la batidora.\n2. Bate durante 30-45 segundos hasta obtener una mezcla cremosa.\n3. Sirve inmediatamente.",
            ],
            [
                'name'                  => 'Bowl de yogur con granola',
                'description'           => 'Bol fresco y saciante con yogur griego, granola y fruta fresca.',
                'category'              => 'desayuno',
                'calories_per_serving'  => 350,
                'protein_per_serving'   => 18,
                'carbs_per_serving'     => 48,
                'fat_per_serving'       => 9,
                'fiber_per_serving'     => 4,
                'servings'              => 1,
                'prep_time_min'         => 3,
                'cook_time_min'         => 0,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Yogur griego natural 0%', 'quantity' => '200g'],
                    ['name' => 'Granola', 'quantity' => '40g'],
                    ['name' => 'Fresas', 'quantity' => '100g'],
                    ['name' => 'Miel', 'quantity' => '1 cucharadita'],
                ],
                'instructions'          => "1. Vierte el yogur en un bol.\n2. Añade la granola por encima.\n3. Corta las fresas y distribúyelas.\n4. Termina con un chorrito de miel.",
            ],

            // =====================================================================
            // ALMUERZOS
            // =====================================================================
            [
                'name'                  => 'Pollo a la plancha con arroz y brócoli',
                'description'           => 'El clásico de todo deportista. Simple, equilibrado y muy efectivo.',
                'category'              => 'almuerzo',
                'calories_per_serving'  => 490,
                'protein_per_serving'   => 48,
                'carbs_per_serving'     => 52,
                'fat_per_serving'       => 8,
                'fiber_per_serving'     => 5,
                'servings'              => 1,
                'prep_time_min'         => 5,
                'cook_time_min'         => 25,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Pechuga de pollo', 'quantity' => '200g'],
                    ['name' => 'Arroz blanco crudo', 'quantity' => '80g'],
                    ['name' => 'Brócoli', 'quantity' => '200g'],
                    ['name' => 'Aceite de oliva', 'quantity' => '1 cucharada'],
                    ['name' => 'Sal, ajo y especias', 'quantity' => 'al gusto'],
                ],
                'instructions'          => "1. Cuece el arroz en abundante agua con sal según las instrucciones del paquete (15-18 min).\n2. Mientras tanto, cuece el brócoli al vapor o en agua hirviendo 5-7 minutos hasta que esté al dente.\n3. Sazona la pechuga de pollo con sal, ajo y las especias que prefieras.\n4. Cocina el pollo en una plancha o sartén con aceite de oliva, 4-5 minutos por cada lado.\n5. Sirve el pollo junto al arroz y el brócoli.",
            ],
            [
                'name'                  => 'Ensalada César con pollo',
                'description'           => 'Ensalada clásica con lechuga romana, pollo a la plancha y aderezo César ligero.',
                'category'              => 'almuerzo',
                'calories_per_serving'  => 380,
                'protein_per_serving'   => 38,
                'carbs_per_serving'     => 12,
                'fat_per_serving'       => 20,
                'fiber_per_serving'     => 3,
                'servings'              => 1,
                'prep_time_min'         => 10,
                'cook_time_min'         => 10,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Pechuga de pollo', 'quantity' => '150g'],
                    ['name' => 'Lechuga romana', 'quantity' => '150g'],
                    ['name' => 'Queso parmesano rallado', 'quantity' => '20g'],
                    ['name' => 'Crutones de pan', 'quantity' => '30g'],
                    ['name' => 'Mayonesa light', 'quantity' => '2 cucharadas'],
                    ['name' => 'Limón', 'quantity' => '1/2 unidad'],
                ],
                'instructions'          => "1. Cocina el pollo a la plancha con sal y pimienta, 5 min por cada lado. Deja enfriar y corta en tiras.\n2. Prepara la salsa: mezcla mayonesa, zumo de limón, un poco de ajo en polvo y parmesano rallado.\n3. Trocea la lechuga y mezcla con la salsa.\n4. Añade el pollo, los crutones y el parmesano restante por encima.",
            ],
            [
                'name'                  => 'Arroz integral con salmón y espinacas',
                'description'           => 'Plato completo rico en omega-3 y hierro, con arroz integral como base.',
                'category'              => 'almuerzo',
                'calories_per_serving'  => 520,
                'protein_per_serving'   => 38,
                'carbs_per_serving'     => 55,
                'fat_per_serving'       => 15,
                'fiber_per_serving'     => 5,
                'servings'              => 1,
                'prep_time_min'         => 5,
                'cook_time_min'         => 30,
                'difficulty'            => 'media',
                'ingredients'           => [
                    ['name' => 'Salmón fresco', 'quantity' => '150g'],
                    ['name' => 'Arroz integral crudo', 'quantity' => '70g'],
                    ['name' => 'Espinacas frescas', 'quantity' => '100g'],
                    ['name' => 'Aceite de oliva', 'quantity' => '1 cucharada'],
                    ['name' => 'Limón', 'quantity' => '1/2 unidad'],
                ],
                'instructions'          => "1. Cuece el arroz integral (20-25 min en agua con sal).\n2. En una sartén con aceite de oliva, saltea las espinacas 2-3 minutos hasta que se reduzcan.\n3. En otra sartén, cocina el salmón al punto con sal y un chorrito de limón, 3-4 min por cada lado.\n4. Sirve el arroz con las espinacas y el salmón encima.",
            ],
            [
                'name'                  => 'Pasta con atún y tomate',
                'description'           => 'Receta rápida y económica con pasta, atún y salsa de tomate casera.',
                'category'              => 'almuerzo',
                'calories_per_serving'  => 450,
                'protein_per_serving'   => 35,
                'carbs_per_serving'     => 55,
                'fat_per_serving'       => 8,
                'fiber_per_serving'     => 4,
                'servings'              => 1,
                'prep_time_min'         => 5,
                'cook_time_min'         => 15,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Pasta (espagueti o penne)', 'quantity' => '80g cruda'],
                    ['name' => 'Atún al natural (lata)', 'quantity' => '150g (escurrido)'],
                    ['name' => 'Tomate triturado', 'quantity' => '150g'],
                    ['name' => 'Aceite de oliva', 'quantity' => '1 cucharada'],
                    ['name' => 'Ajo', 'quantity' => '1 diente'],
                    ['name' => 'Orégano y sal', 'quantity' => 'al gusto'],
                ],
                'instructions'          => "1. Cuece la pasta en agua hirviendo con sal según instrucciones del paquete.\n2. En una sartén, sofríe el ajo picado en aceite de oliva 1 minuto.\n3. Añade el tomate triturado, orégano y sal. Cocina 5-7 minutos a fuego medio.\n4. Incorpora el atún escurrido y mezcla bien.\n5. Escurre la pasta y añádela a la sartén. Mezcla todo junto 1 minuto.",
            ],
            [
                'name'                  => 'Bowl de quinoa con pollo y verduras',
                'description'           => 'Bowl nutritivo con quinoa (proteína completa), pollo y verduras asadas.',
                'category'              => 'almuerzo',
                'calories_per_serving'  => 470,
                'protein_per_serving'   => 42,
                'carbs_per_serving'     => 45,
                'fat_per_serving'       => 12,
                'fiber_per_serving'     => 7,
                'servings'              => 1,
                'prep_time_min'         => 10,
                'cook_time_min'         => 25,
                'difficulty'            => 'media',
                'ingredients'           => [
                    ['name' => 'Quinoa cruda', 'quantity' => '70g'],
                    ['name' => 'Pechuga de pollo', 'quantity' => '150g'],
                    ['name' => 'Pimiento rojo', 'quantity' => '100g'],
                    ['name' => 'Calabacín', 'quantity' => '100g'],
                    ['name' => 'Aceite de oliva', 'quantity' => '1 cucharada'],
                    ['name' => 'Limón', 'quantity' => '1/2 unidad'],
                ],
                'instructions'          => "1. Cuece la quinoa: 1 parte de quinoa por 2 de agua, 15 min a fuego bajo.\n2. Corta el pimiento y el calabacín en trozos medianos. Ásalos en el horno a 200°C con aceite y sal durante 20 min.\n3. Cocina el pollo a la plancha sazonado con sal y especias.\n4. Monta el bowl: quinoa + verduras + pollo en tiras. Aliña con limón y un poco de aceite.",
            ],
            [
                'name'                  => 'Lentejas estofadas',
                'description'           => 'Guiso tradicional de lentejas con verduras, rico en proteína vegetal y fibra.',
                'category'              => 'almuerzo',
                'calories_per_serving'  => 340,
                'protein_per_serving'   => 22,
                'carbs_per_serving'     => 55,
                'fat_per_serving'       => 4,
                'fiber_per_serving'     => 14,
                'servings'              => 2,
                'prep_time_min'         => 10,
                'cook_time_min'         => 35,
                'difficulty'            => 'media',
                'ingredients'           => [
                    ['name' => 'Lentejas pardinas', 'quantity' => '200g (crudas)'],
                    ['name' => 'Zanahoria', 'quantity' => '1 unidad'],
                    ['name' => 'Cebolla', 'quantity' => '1/2 unidad'],
                    ['name' => 'Tomate triturado', 'quantity' => '100g'],
                    ['name' => 'Pimiento verde', 'quantity' => '1/2 unidad'],
                    ['name' => 'Aceite de oliva', 'quantity' => '1 cucharada'],
                    ['name' => 'Pimentón, sal, comino', 'quantity' => 'al gusto'],
                ],
                'instructions'          => "1. Pica la cebolla, zanahoria y pimiento en trozos pequeños.\n2. Sofríe en aceite de oliva 5 min. Añade el tomate y cocina 3 min más.\n3. Añade las lentejas enjuagadas y cubre con agua (el doble de volumen).\n4. Agrega el pimentón, comino y sal. Cocina a fuego medio 25-30 min hasta que las lentejas estén tiernas.",
            ],
            [
                'name'                  => 'Tortilla española',
                'description'           => 'El clásico español: tortilla de patatas y huevos, saciante y nutritiva.',
                'category'              => 'almuerzo',
                'calories_per_serving'  => 380,
                'protein_per_serving'   => 18,
                'carbs_per_serving'     => 30,
                'fat_per_serving'       => 20,
                'fiber_per_serving'     => 2,
                'servings'              => 2,
                'prep_time_min'         => 10,
                'cook_time_min'         => 20,
                'difficulty'            => 'media',
                'ingredients'           => [
                    ['name' => 'Huevos', 'quantity' => '4 unidades'],
                    ['name' => 'Patata', 'quantity' => '300g'],
                    ['name' => 'Cebolla', 'quantity' => '1/2 unidad'],
                    ['name' => 'Aceite de oliva', 'quantity' => '3 cucharadas'],
                    ['name' => 'Sal', 'quantity' => 'al gusto'],
                ],
                'instructions'          => "1. Pela y corta las patatas en láminas finas. Pica la cebolla.\n2. Fríe las patatas y cebolla en abundante aceite a fuego medio durante 15-20 min hasta que estén tiernas (no crujientes).\n3. Escurre bien el aceite. Bate los huevos con sal y añade las patatas. Mezcla bien.\n4. En una sartén antiadherente con un poco de aceite, vierte la mezcla a fuego medio. Cuaja 3-4 min.\n5. Voltea con ayuda de un plato y cuaja por el otro lado 2-3 minutos.",
            ],

            // =====================================================================
            // CENAS
            // =====================================================================
            [
                'name'                  => 'Salmón al horno con patata y espárragos',
                'description'           => 'Cena completa y equilibrada, fácil de preparar y lista en 30 minutos.',
                'category'              => 'cena',
                'calories_per_serving'  => 480,
                'protein_per_serving'   => 36,
                'carbs_per_serving'     => 35,
                'fat_per_serving'       => 20,
                'fiber_per_serving'     => 5,
                'servings'              => 1,
                'prep_time_min'         => 5,
                'cook_time_min'         => 25,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Salmón (filete)', 'quantity' => '180g'],
                    ['name' => 'Patata', 'quantity' => '200g'],
                    ['name' => 'Espárragos verdes', 'quantity' => '100g'],
                    ['name' => 'Aceite de oliva', 'quantity' => '1 cucharada'],
                    ['name' => 'Limón, sal, eneldo', 'quantity' => 'al gusto'],
                ],
                'instructions'          => "1. Precalienta el horno a 200°C.\n2. Corta las patatas en gajos, unta con aceite y sal. Hornea 15 min.\n3. Añade los espárragos y el salmón aliñado con limón, sal y eneldo.\n4. Hornea 12-15 minutos más hasta que el salmón esté listo.",
            ],
            [
                'name'                  => 'Ensalada de garbanzos con atún',
                'description'           => 'Ensalada fría y proteica, perfecta como cena ligera post-entreno.',
                'category'              => 'cena',
                'calories_per_serving'  => 380,
                'protein_per_serving'   => 30,
                'carbs_per_serving'     => 38,
                'fat_per_serving'       => 10,
                'fiber_per_serving'     => 10,
                'servings'              => 1,
                'prep_time_min'         => 10,
                'cook_time_min'         => 0,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Garbanzos cocidos (bote)', 'quantity' => '200g'],
                    ['name' => 'Atún al natural', 'quantity' => '120g (escurrido)'],
                    ['name' => 'Tomate cherry', 'quantity' => '100g'],
                    ['name' => 'Pepino', 'quantity' => '1/2 unidad'],
                    ['name' => 'Aceite de oliva', 'quantity' => '1 cucharada'],
                    ['name' => 'Limón y sal', 'quantity' => 'al gusto'],
                ],
                'instructions'          => "1. Escurre y enjuaga los garbanzos.\n2. Corta los tomates por la mitad y el pepino en rodajas.\n3. Mezcla todo en un bol con el atún.\n4. Aliña con aceite de oliva, zumo de limón y sal.",
            ],
            [
                'name'                  => 'Crema de verduras',
                'description'           => 'Sopa cremosa de verduras de temporada, baja en calorías y reconfortante.',
                'category'              => 'cena',
                'calories_per_serving'  => 180,
                'protein_per_serving'   => 5,
                'carbs_per_serving'     => 28,
                'fat_per_serving'       => 5,
                'fiber_per_serving'     => 6,
                'servings'              => 2,
                'prep_time_min'         => 10,
                'cook_time_min'         => 25,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Calabacín', 'quantity' => '300g'],
                    ['name' => 'Zanahoria', 'quantity' => '2 unidades'],
                    ['name' => 'Cebolla', 'quantity' => '1/2 unidad'],
                    ['name' => 'Patata', 'quantity' => '100g'],
                    ['name' => 'Caldo de verduras', 'quantity' => '500ml'],
                    ['name' => 'Aceite de oliva', 'quantity' => '1 cucharada'],
                ],
                'instructions'          => "1. Pica todas las verduras en trozos medianos.\n2. Sofríe la cebolla en aceite 3 min. Añade el resto de verduras y saltea 2 min.\n3. Añade el caldo y cocina 20 min a fuego medio.\n4. Tritura con una batidora de mano hasta obtener una crema lisa. Ajusta de sal.",
            ],
            [
                'name'                  => 'Merluza al vapor con verduras',
                'description'           => 'Cena muy ligera y saludable, baja en grasas y alta en proteína.',
                'category'              => 'cena',
                'calories_per_serving'  => 230,
                'protein_per_serving'   => 32,
                'carbs_per_serving'     => 12,
                'fat_per_serving'       => 6,
                'fiber_per_serving'     => 4,
                'servings'              => 1,
                'prep_time_min'         => 5,
                'cook_time_min'         => 15,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Merluza (filete)', 'quantity' => '200g'],
                    ['name' => 'Brócoli', 'quantity' => '150g'],
                    ['name' => 'Zanahoria', 'quantity' => '1 unidad'],
                    ['name' => 'Aceite de oliva', 'quantity' => '1 cucharadita'],
                    ['name' => 'Limón y sal', 'quantity' => 'al gusto'],
                ],
                'instructions'          => "1. Corta el brócoli en ramilletes y la zanahoria en bastones.\n2. Cuece las verduras al vapor 8-10 min.\n3. En la vaporera o en agua hirviendo tapada, cocina la merluza 5-7 min.\n4. Sirve el pescado sobre las verduras con un chorrito de aceite y limón.",
            ],
            [
                'name'                  => 'Revuelto de huevos con espinacas y champiñones',
                'description'           => 'Cena rápida y proteica lista en 10 minutos.',
                'category'              => 'cena',
                'calories_per_serving'  => 290,
                'protein_per_serving'   => 22,
                'carbs_per_serving'     => 8,
                'fat_per_serving'       => 19,
                'fiber_per_serving'     => 3,
                'servings'              => 1,
                'prep_time_min'         => 3,
                'cook_time_min'         => 7,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Huevos', 'quantity' => '3 unidades'],
                    ['name' => 'Espinacas frescas', 'quantity' => '100g'],
                    ['name' => 'Champiñones', 'quantity' => '100g'],
                    ['name' => 'Aceite de oliva', 'quantity' => '1 cucharadita'],
                    ['name' => 'Ajo, sal y pimienta', 'quantity' => 'al gusto'],
                ],
                'instructions'          => "1. Lámina los champiñones y saltéalos en aceite con ajo picado 3-4 min.\n2. Añade las espinacas y cocina 2 min hasta que se reduzcan.\n3. Bate los huevos con sal y pimienta, incorpóralos a la sartén.\n4. Remueve constantemente a fuego bajo hasta conseguir el punto de cuajado deseado.",
            ],

            // =====================================================================
            // SNACKS
            // =====================================================================
            [
                'name'                  => 'Hummus con palitos de verduras',
                'description'           => 'Snack saciante y nutritivo con hummus casero y bastones de verdura cruda.',
                'category'              => 'snack',
                'calories_per_serving'  => 210,
                'protein_per_serving'   => 9,
                'carbs_per_serving'     => 22,
                'fat_per_serving'       => 10,
                'fiber_per_serving'     => 7,
                'servings'              => 1,
                'prep_time_min'         => 10,
                'cook_time_min'         => 0,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Garbanzos cocidos', 'quantity' => '150g'],
                    ['name' => 'Tahini (pasta de sésamo)', 'quantity' => '1 cucharada'],
                    ['name' => 'Limón', 'quantity' => '1/2 unidad'],
                    ['name' => 'Ajo', 'quantity' => '1 diente'],
                    ['name' => 'Zanahoria', 'quantity' => '1 unidad'],
                    ['name' => 'Pepino', 'quantity' => '1/2 unidad'],
                ],
                'instructions'          => "1. Tritura los garbanzos con el tahini, zumo de limón, ajo y una pizca de sal. Añade agua si queda muy espeso.\n2. Corta la zanahoria y el pepino en bastones.\n3. Sirve el hummus con los palitos de verdura para mojar.",
            ],
            [
                'name'                  => 'Manzana con mantequilla de almendras',
                'description'           => 'Snack rápido con buena combinación de carbohidratos y grasas saludables.',
                'category'              => 'snack',
                'calories_per_serving'  => 220,
                'protein_per_serving'   => 5,
                'carbs_per_serving'     => 28,
                'fat_per_serving'       => 11,
                'fiber_per_serving'     => 5,
                'servings'              => 1,
                'prep_time_min'         => 2,
                'cook_time_min'         => 0,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Manzana', 'quantity' => '1 unidad (180g)'],
                    ['name' => 'Mantequilla de almendras', 'quantity' => '2 cucharadas (30g)'],
                ],
                'instructions'          => "1. Corta la manzana en gajos.\n2. Sirve con la mantequilla de almendras para mojar.",
            ],
            [
                'name'                  => 'Tortitas de arroz con queso fresco y aguacate',
                'description'           => 'Snack ligero y saciante con buena combinación de macros.',
                'category'              => 'snack',
                'calories_per_serving'  => 195,
                'protein_per_serving'   => 8,
                'carbs_per_serving'     => 22,
                'fat_per_serving'       => 9,
                'fiber_per_serving'     => 3,
                'servings'              => 1,
                'prep_time_min'         => 3,
                'cook_time_min'         => 0,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Tortitas de arroz', 'quantity' => '3 unidades (30g)'],
                    ['name' => 'Queso fresco', 'quantity' => '50g'],
                    ['name' => 'Aguacate', 'quantity' => '1/4 unidad (40g)'],
                    ['name' => 'Sal y pimienta', 'quantity' => 'al gusto'],
                ],
                'instructions'          => "1. Extiende el queso fresco sobre las tortitas.\n2. Añade láminas de aguacate.\n3. Sazona con sal y pimienta.",
            ],
            [
                'name'                  => 'Batido de plátano y cacao',
                'description'           => 'Batido dulce y nutritivo, perfecto antes o después del entreno.',
                'category'              => 'snack',
                'calories_per_serving'  => 270,
                'protein_per_serving'   => 12,
                'carbs_per_serving'     => 40,
                'fat_per_serving'       => 6,
                'fiber_per_serving'     => 4,
                'servings'              => 1,
                'prep_time_min'         => 3,
                'cook_time_min'         => 0,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Plátano', 'quantity' => '1 unidad (100g)'],
                    ['name' => 'Leche semidesnatada', 'quantity' => '200ml'],
                    ['name' => 'Cacao puro en polvo', 'quantity' => '1 cucharada'],
                    ['name' => 'Proteína whey', 'quantity' => '15g (opcional)'],
                ],
                'instructions'          => "1. Añade todos los ingredientes en la batidora.\n2. Bate 30 segundos hasta que quede cremoso.\n3. Sirve frío.",
            ],
            [
                'name'                  => 'Yogur con almendras y miel',
                'description'           => 'Snack simple y rápido, ideal a media mañana o tarde.',
                'category'              => 'snack',
                'calories_per_serving'  => 240,
                'protein_per_serving'   => 14,
                'carbs_per_serving'     => 22,
                'fat_per_serving'       => 11,
                'fiber_per_serving'     => 2,
                'servings'              => 1,
                'prep_time_min'         => 1,
                'cook_time_min'         => 0,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Yogur griego natural 0%', 'quantity' => '180g'],
                    ['name' => 'Almendras', 'quantity' => '20g'],
                    ['name' => 'Miel', 'quantity' => '1 cucharadita'],
                ],
                'instructions'          => "1. Vierte el yogur en un bol.\n2. Añade las almendras y la miel por encima.",
            ],

            // =====================================================================
            // RECETAS PARA GANAR MASA MUSCULAR (más calóricas)
            // =====================================================================
            [
                'name'                  => 'Bowl de arroz con carne y aguacate',
                'description'           => 'Bowl hipercalórico ideal para días de entreno intenso o para ganar masa.',
                'category'              => 'almuerzo',
                'calories_per_serving'  => 720,
                'protein_per_serving'   => 48,
                'carbs_per_serving'     => 68,
                'fat_per_serving'       => 24,
                'fiber_per_serving'     => 7,
                'servings'              => 1,
                'prep_time_min'         => 5,
                'cook_time_min'         => 20,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Arroz blanco crudo', 'quantity' => '100g'],
                    ['name' => 'Carne picada de ternera', 'quantity' => '150g'],
                    ['name' => 'Aguacate', 'quantity' => '1/2 unidad (80g)'],
                    ['name' => 'Maíz dulce', 'quantity' => '50g'],
                    ['name' => 'Aceite de oliva', 'quantity' => '1 cucharada'],
                ],
                'instructions'          => "1. Cuece el arroz en agua con sal.\n2. Saltea la carne picada en sartén con aceite y sal hasta que esté cocinada.\n3. Monta el bowl: arroz + carne + aguacate en láminas + maíz.\n4. Puedes añadir salsa de soja o sriracha al gusto.",
            ],
            [
                'name'                  => 'Pasta con pollo y salsa de cacahuete',
                'description'           => 'Receta asiática de alto valor calórico, perfecta para volumen.',
                'category'              => 'almuerzo',
                'calories_per_serving'  => 680,
                'protein_per_serving'   => 52,
                'carbs_per_serving'     => 65,
                'fat_per_serving'       => 22,
                'fiber_per_serving'     => 5,
                'servings'              => 1,
                'prep_time_min'         => 5,
                'cook_time_min'         => 15,
                'difficulty'            => 'media',
                'ingredients'           => [
                    ['name' => 'Pasta (penne o espagueti)', 'quantity' => '100g cruda'],
                    ['name' => 'Pechuga de pollo', 'quantity' => '180g'],
                    ['name' => 'Mantequilla de cacahuete', 'quantity' => '2 cucharadas'],
                    ['name' => 'Salsa de soja', 'quantity' => '1 cucharada'],
                    ['name' => 'Lima o limón', 'quantity' => '1/2 unidad'],
                ],
                'instructions'          => "1. Cuece la pasta según instrucciones. Reserva 2 cucharadas del agua de cocción.\n2. Cocina el pollo a la plancha y córtalo en tiras.\n3. Prepara la salsa: mezcla mantequilla de cacahuete + soja + zumo de lima + agua de pasta hasta obtener una salsa líquida.\n4. Mezcla la pasta con el pollo y la salsa.",
            ],

            // =====================================================================
            // RECETAS PARA DIETA / BAJAR PESO (bajas en calorías)
            // =====================================================================
            [
                'name'                  => 'Ensalada de pollo con vinagreta de mostaza',
                'description'           => 'Ensalada saciante y baja en calorías para días de déficit.',
                'category'              => 'almuerzo',
                'calories_per_serving'  => 290,
                'protein_per_serving'   => 35,
                'carbs_per_serving'     => 10,
                'fat_per_serving'       => 12,
                'fiber_per_serving'     => 4,
                'servings'              => 1,
                'prep_time_min'         => 10,
                'cook_time_min'         => 10,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Pechuga de pollo', 'quantity' => '150g'],
                    ['name' => 'Lechuga variada', 'quantity' => '100g'],
                    ['name' => 'Tomate cherry', 'quantity' => '100g'],
                    ['name' => 'Rábanos', 'quantity' => '50g'],
                    ['name' => 'Mostaza Dijon', 'quantity' => '1 cucharadita'],
                    ['name' => 'Aceite de oliva', 'quantity' => '1 cucharadita'],
                    ['name' => 'Vinagre balsámico', 'quantity' => '1 cucharadita'],
                ],
                'instructions'          => "1. Cocina el pollo a la plancha con sal y especias. Deja enfriar y corta en tiras.\n2. Prepara la vinagreta: mezcla mostaza + aceite + vinagre + sal.\n3. Mezcla la lechuga con los tomates y rábanos.\n4. Añade el pollo y aliña con la vinagreta.",
            ],
            [
                'name'                  => 'Caldo de pollo con verduras',
                'description'           => 'Sopa calórica muy baja, reconfortante y saciante por volumen.',
                'category'              => 'cena',
                'calories_per_serving'  => 120,
                'protein_per_serving'   => 15,
                'carbs_per_serving'     => 10,
                'fat_per_serving'       => 2,
                'fiber_per_serving'     => 3,
                'servings'              => 2,
                'prep_time_min'         => 10,
                'cook_time_min'         => 30,
                'difficulty'            => 'fácil',
                'ingredients'           => [
                    ['name' => 'Pechuga de pollo', 'quantity' => '200g'],
                    ['name' => 'Zanahoria', 'quantity' => '2 unidades'],
                    ['name' => 'Apio', 'quantity' => '2 ramas'],
                    ['name' => 'Cebolla', 'quantity' => '1/2 unidad'],
                    ['name' => 'Ajo', 'quantity' => '2 dientes'],
                    ['name' => 'Sal, pimienta, perejil', 'quantity' => 'al gusto'],
                ],
                'instructions'          => "1. En una olla grande, añade el pollo con 1.5 litros de agua fría.\n2. Añade la cebolla partida, ajo, zanahoria en trozos y apio.\n3. Lleva a ebullición, retira la espuma y cocina a fuego bajo 25-30 min.\n4. Saca el pollo, desmenúzalo y vuelve a incorporarlo.\n5. Ajusta de sal y añade perejil picado.",
            ],
        ];

        // Insertamos todas las recetas
        foreach ($recipes as $recipe) {
            Recipe::create(array_merge($recipe, [
                'is_system' => true,
                'user_id'   => null,
            ]));
        }

        $this->command->info('✅ Seeder de recetas completado: ' . count($recipes) . ' recetas cargadas.');
    }
}
